name: SabakaLang-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Workloads
        run: dotnet workload restore

      - name: Restore
        run: dotnet restore -r linux-x64 -p:UseMaui=false -p:EnableWindowsTargeting=true

      - name: Build
        run: ls src/**/*.csproj tests/**/*.csproj | grep -v "Studio" | xargs -I {} dotnet build {} --no-restore --configuration Release --os linux /p:TreatWarningsAsErrors=true

      - name: Test
        run: |
          mkdir -p ./TestResults
          # Ищем DLL тестовых проектов внутри новой папки tests/
          find tests/ -type f -name "*UnitTests.dll" -path "*/bin/Release/*" | while read -r test_dll; do
            echo "Running tests in: $test_dll"
            dotnet exec "$test_dll"
          done

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Workloads
        run: dotnet workload restore

      - name: Restore
        run: dotnet restore -r win-x64 -p:UseMaui=false -p:EnableWindowsTargeting=true

      - name: Build
        run: ls src/**/*.csproj tests/**/*.csproj | grep -v "Studio" | xargs -I {} dotnet build {} --no-restore --configuration Release /p:TreatWarningsAsErrors=true

  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Workloads
        run: dotnet workload restore

      - name: Restore
        run: dotnet restore -r linux-x64 -p:UseMaui=false -p:EnableWindowsTargeting=true

      - name: Build
        run: ls src/**/*.csproj tests/**/*.csproj | grep -v "Studio" | xargs -I {} dotnet build {} --no-restore --configuration Release --os linux /p:TreatWarningsAsErrors=true

      - name: Cover
        run: |
          dotnet tool install --global dotnet-coverage
          mkdir -p ./TestResults
          # Ищем DLL тестовых проектов внутри новой папки tests/
          find tests/ -type f -name "*UnitTests.dll" -path "*/bin/Release/*" | while read -r test_dll; do
            echo "Running coverage for: $test_dll"
            proj_name=$(basename "$test_dll" .dll)
            mkdir -p "./TestResults/$proj_name"
            dotnet-coverage collect \
              --output "./TestResults/$proj_name/coverage.cobertura.xml" \
              --output-format cobertura \
              dotnet exec "$test_dll"
          done

      - name: Merge Reports & Create Summary
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: './TestResults/**/coverage.cobertura.xml'
          targetdir: 'merged_coverage'
          reporttypes: 'MarkdownSummary'

      - name: Write Summary to Commit
        run: |
          if [ -f "merged_coverage/Summary.md" ]; then
            cat merged_coverage/Summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Summary doesn't exist" >> $GITHUB_STEP_SUMMARY
          fi

  versions-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install sabaka-chabaka/NugetSpy
        run: dotnet tool install --global sabaka-chabaka.NugetSpy --version 1.0.5

      - name: Run NugetSpy and write summary
        if: always()
        run: |
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "### NuGet Spy Analysis Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> \$GITHUB_STEP_SUMMARY
          NO_COLOR=1 nuget-spy >> \$GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  build-deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test, build-check, cover, versions-check]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Workloads
        run: dotnet workload restore

      - name: Restore
        run: dotnet restore -r win-x64 -p:UseMaui=false -p:EnableWindowsTargeting=true

      - name: Publish Cli
        run: dotnet publish src/SabakaLang.Cli/SabakaLang.Cli.csproj -c Release -r win-x64 -o ./publish-cli --no-restore /p:EnableWindowsTargeting=true

      - name: Publish Runner
        run: dotnet publish src/SabakaLang.Runner/SabakaLang.Runner.csproj -c Release -r win-x64 -o ./publish-runner --no-restore /p:EnableWindowsTargeting=true

      - name: Publish Language Server
        run: dotnet publish src/SabakaLang.LanguageServer/SabakaLang.LanguageServer.csproj -c Release -r win-x64 -o ./publish-lsp --no-restore /p:EnableWindowsTargeting=true

      - name: Upload Cli Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SabakaLang-Cli
          path: ./publish-cli/

      - name: Upload Runner Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SabakaLang-Runner
          path: ./publish-runner/

      - name: Upload Language Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SabakaLang-LanguageServer
          path: ./publish-lsp/
